# Generated by Django 2.2.4 on 2019-09-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibMysql', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=32)),
                ('classname', models.CharField(max_length=32)),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
