# Generated by Django 2.2.4 on 2019-09-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibMysql', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=60)),
                ('bookid', models.CharField(max_length=12)),
                ('author', models.CharField(max_length=32)),
                ('bookinfo', models.TextField()),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
