# Generated by Django 2.2.4 on 2019-09-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibMysql', '0003_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookinfo',
            field=models.CharField(max_length=255),
        ),
    ]
