# Generated by Django 2.2.4 on 2019-09-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibMysql', '0006_auto_20190903_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField(verbose_name=3)),
                ('bookid', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='HaveClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField(verbose_name=3)),
                ('typename', models.CharField(max_length=32)),
            ],
        ),
    ]
