# Generated by Django 2.2.4 on 2019-09-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibMysql', '0007_bookclassify_haveclassify'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField(verbose_name=1)),
                ('bookid', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='HaveBookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField(verbose_name=1)),
                ('typename', models.CharField(max_length=32)),
            ],
        ),
    ]
