# Generated by Django 2.2.5 on 2019-09-05 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibMysql', '0008_booktype_havebooktype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookType',
            new_name='BookState',
        ),
        migrations.RenameModel(
            old_name='HaveBookType',
            new_name='HaveBookState',
        ),
    ]
