# Generated by Django 2.2.5 on 2019-09-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibMysql', '0010_auto_20190905_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowMaxBookNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('num', models.IntegerField(verbose_name=2)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowNowBookNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('num', models.IntegerField(verbose_name=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
