# Generated by Django 2.2.5 on 2019-09-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibMysql', '0011_auto_20190906_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='intro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='qq',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='weibo',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
